[package]
name = "mono_types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.26", features = ["serde"] }
typeshare = "1.0.1"
uuid = { version = "1.4.1", features = ["v5", "v4"] }
